// ヘッダー共通部品を直接書き出す
(function() {
  var headerHTML = ''
    + '<header>'
    + '<div class="bg_bl"></div>'
    + '<div class="rogo">'
    + '    <h1><a href="index.html"><img src="image/ロゴ3.png" alt="ロゴ"></a></h1>'
    + '</div>'
    + '<a class="menu_btn">'
    + '    <span class="top"></span>'
    + '    <span class="middle"></span>'
    + '    <span class="bottom"></span>'
    + '</a>'
    + '<div class="h_btn"><a href="contact.html"><i class="fas fa-envelope"></i><span>お問合わせ</span></a></div>'
    + '<div class="h_tel font_mincho"><a href="tel:"><i class="fas fa-phone"></i><span>080-<strong>6842-6878</strong></span></a></div>'
    + '<nav id="g_navi">'
    + '    <ul class="navi_base">'
    + '    <li><a href="index.html">HOME</a></li>'
    + '      <li><a class="ac_menu">アプリ作成について</a>'
    + '      <div class="ac_list">'
    + '      <ul>'
    + '      <li><a href="aplisakusei_wedapp.html">webアプリ</a></li>'
    + '      <li><a href="aplisakusei_mobail.html">モバイルアプリ</a></li>'
    + '      <li><a href="aplisakusei_infra.html">インフラ</a></li>'
    + '      </ul>'
    + '      </div>'
    + '      </li>'
    // + '      <li><a class="ac_menu">作成例</a>'
    // + '      <div class="ac_list">'
    // + '      <ul>'
    // + '      <li><a href="works.html">マッチングアプリ（モバイル）</a></li>'
    // + '      <li><a href="works.html">プロジェクト管理（webアプリ）</a></li>'
    // + '      <li><a href="works.html">掲示板（webアプリ）</a></li>'
    // + '      <li><a href="works.html">LINEボット（モバイル）</a></li>'
    // + '      <li><a href="works.html">マッチングアプリ（モバイル）</a></li>'
    // + '      </ul>'
    // + '      </div>'
    // + '      </li>'
    + '      <li><a href="faq.html">FAQ</a></li>'
    + '      <li><a href="company.html">会社案内</a>'
    + '      <div class="ac_list">'
    + '      <ul>'
    + '      <li><a href="company.html">会社概要</a></li>'
    + '      <li><a href="tokushoho.html">特定商取引法に基づく表記</a></li>'
    + '      <li><a href="privacy-policy.html">プライバシーポリシー</a></li>'
    + '      </ul>'
    + '      </div>'
    + '      </li>'
    + '    </ul>'
    + '</nav>'
    + '</header>';

  document.getElementById('header-placeholder').innerHTML = headerHTML;
})();
